### ISSUE TITLE
It's Fucked

### ISSUE THREAD

**Issue by Scrxtchy** [Facepunch/webrcon#10]
http://facepunch.github.io/webrcon/
![](https://upload.teknik.io/V3VVE.png)
![](https://upload.teknik.io/DHCDp.png)

👏🏼Github

**Comment by Dids** [comment]
Works fine here?

**Comment by Cyanide-ghs** [comment]
Tried it on our new vanilla server and it seemed to crap our server out when RCON was connected. :/

**Comment by Dids** [comment]
Make sure you're using webrcon, not the old rcon, as it works fine here (vanilla).
