### ISSUE TITLE
Error when trying to view player XP charts.

### ISSUE THREAD

**Issue by Visagalis** [Facepunch/webrcon#7]
Error:

> TypeError: Cannot read property 'length' of null
>     at SVGGElement.<anonymous> (nv.d3.js:5654)
>     at d3.js:962
>     at d3_selection_each (d3.js:968)
>     at Array.d3_selectionPrototype.each (d3.js:961)
>     at SVGGElement.<anonymous> (nv.d3.js:5652)
>     at d3.js:962
>     at d3_selection_each (d3.js:968)
>     at Array.d3_selectionPrototype.each (d3.js:961)
>     at Array.chart (nv.d3.js:5498)
>     at Array.d3_selectionPrototype.call (d3.js:975)(anonymous function) @ angular.js:12520

Call stack: 
![sttgfk 1](https://cloud.githubusercontent.com/assets/574613/16202051/c9fa6126-371c-11e6-9a00-24b0b46fff38.png)

**Comment by Dids** [comment]
This can be closed. ;)
