### ISSUE TITLE
Error 1006

### ISSUE THREAD

**Issue by ghost** [Facepunch/webrcon#9]
Hey so recently ive been looking for a web rcon so i tried this But when i try to connect it says

Connection was Closed - Error 1006

please Help since i really need this

**Comment by Evil-Raveen** [comment]
you have to set the server setting +rcon.web true
rcon.password should not contain characters @#$-=()*^%

**Comment by ghost** [comment]
I thought you only had to do that to rust im doing this to source games like gmod
